version: '3.8'

services:
  # MongoDB Service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # NATS Service
  nats:
    image: nats:latest
    container_name: nats
    ports:
      - "4222:4222"
    networks:
      - backend

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - backend

  # Java Spring Boot Application
  springboot:
    container_name: springboot
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - MONGO_URI=mongodb://root:example@mongodb:27017/chat_app?authSource=admin
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
    networks:
      - backend
    depends_on:
      - mongodb
      - nats
      - redis
    volumes:
      - .:/app    # Mount the project directory for hot reloading

networks:
  backend:
    driver: bridge

volumes:
  mongo_data:
